### ISSUE TITLE
Add local network deploy argument

### ISSUE THREAD

**Issue by mortimr** [Lamarkaz/parasol#1]
Hi,

I was wondering what you think of the idea of adding a `local` argument to deploy, in the case where we would only like to deploy the smart contracts on a local node that was launched outside of `parasol`.
We would have an optional `local` configuration with the `port` and the `coinbase` as hex address or index.

What do you think about that ?

**Comment by nourharidy** [comment]
Although not yet officially documented, you can already use a custom endpoint when deploying, for example:
`parasol deploy http://localhost:8545`
and for interacting with contracts:
`parasol interact http://localhost:8545`
Developing on a separate network though is not supported by Parasol. This is a design decision that will later be changed to allow freedom of choice.
