### ISSUE TITLE
Deploy with arguments

### ISSUE THREAD

**Issue by 7flash** [Lamarkaz/parasol#4]
How can I deploy smart contract with arguments in constructor?
```
    tokensale = await contracts['Tokensale.sol:Tokensale'].deploy(1).send(options)
```

     TypeError: Cannot create property 'arguments' on number '1'

**Comment by nourharidy** [comment]
According to [Web3 1.0 docs](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#deploy), here's the correct syntax:

`tokensale = await contracts['Tokensale.sol:Tokensale'].deploy({arguments:[1]}).send(options)
`

**Comment by 7flash** [comment]
Thanks, it works
